# Generated by Django 4.2.1 on 2023-05-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='profile_picture/')),
                ('profile_name', models.CharField(max_length=30)),
                ('youtube_link', models.CharField(max_length=150)),
                ('instagram_link', models.CharField(max_length=150)),
                ('twitter_link', models.CharField(max_length=150)),
                ('linkedin_link', models.CharField(max_length=150)),
                ('skype_link', models.CharField(max_length=150)),
            ],
        ),
    ]
