# Generated by Django 4.2.1 on 2023-05-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='youtube_link',
            new_name='facebook_link',
        ),
    ]
