# Generated by Django 4.2.1 on 2023-05-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_youtube_link_profile_facebook_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_text', models.CharField(max_length=30)),
            ],
        ),
    ]
