# Generated by Django 4.2.1 on 2023-05-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_slidertext'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('about', models.TextField()),
                ('title', models.TextField(max_length=40)),
                ('title_desc_one', models.TextField()),
                ('title_desc_second', models.TextField()),
                ('birthday', models.DateField()),
                ('website', models.CharField(max_length=150)),
                ('phone', models.IntegerField()),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('degree', models.CharField(max_length=50)),
                ('freelance', models.CharField(max_length=50)),
            ],
        ),
    ]
