# Generated by Django 4.2.1 on 2023-05-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_fact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('skill_name', models.CharField(max_length=30)),
                ('skill_percentage', models.IntegerField()),
            ],
        ),
    ]
