# Generated by Django 4.2.1 on 2023-05-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
    ]
