# Generated by Django 4.2.1 on 2023-05-10 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_skill_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('profession_name', models.CharField(max_length=150)),
                ('year_range', models.CharField(max_length=30)),
                ('work_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.resume')),
            ],
        ),
    ]
