# Generated by Django 4.2.1 on 2023-05-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_portfoliocard_portfolioweb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
