# Generated by Django 4.2.1 on 2023-05-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonial/')),
                ('name', models.CharField(max_length=40)),
                ('designation', models.CharField(max_length=40)),
                ('quote', models.TextField()),
            ],
        ),
    ]
