# Generated by Django 4.2.1 on 2023-05-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_desc', models.TextField()),
                ('resume_desc', models.TextField()),
                ('Portfolio_desc', models.TextField()),
                ('service_desc', models.TextField()),
                ('testimonial_desc', models.TextField()),
                ('contact_desc', models.TextField()),
            ],
        ),
    ]
