# Generated by Django 4.2.1 on 2023-05-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designer_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='description',
            old_name='Portfolio_desc',
            new_name='portfolio_desc',
        ),
    ]
