# Generated by Django 4.2.1 on 2023-05-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_copyright_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyright',
            name='designer_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
